### ISSUE TITLE
Prebuilt `MethylationEPIC_CpGtools.tsv.gz` doesn't includes all 450K sites

### ISSUE THREAD

**Issue by albert-ying** [liguowang/cpgtools#2]
Hi, I just realized that the prebuilt file doesn't include all 450K methylation sites. It would be very helpful if you can update it (or release a similar one for only for 450K sites). Thank you!

**Comment by liguowang** [comment]
Yes, this file is 850K centered.  There are about 43000 CpGs from the 450K not covered by 850K. I am not sure if we have time to provide 450K specific annotation file.

**Comment by albert-ying** [comment]
In this case, is it possible to share the script you used to generate the reference file for 850K? So I can replicate the steps for 450K. Thank you!

**Comment by liguowang** [comment]
This file is manually curated. We did not build a pipeline to automate the process. The annotation datasets are all collected from public domain (ENCODE, UCSC, etc).
